format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$line_break\
$python\
$character"""

[directory]
style = "#458588"

[character]
success_symbol = "[❯](#D35D10)"
error_symbol = "[❯](#CC241D)"
vimcmd_symbol = "[❮](#D45D10)"

[git_branch]
format = "[$branch]($style)"
style = "#689D6A"

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed)]($style)"
style = "#97951B"
conflicted = "​"
untracked = "​"
modified = "​"
staged = "​"
renamed = "​"
deleted = "​"
stashed = "≡"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "#6A9B69"

[cmd_duration]
format = "[$duration]($style) "
style = "#D79921"

[python]
format = "[$virtualenv]($style) "
style = "#D79921"
